### ISSUE TITLE
new name for project

### ISSUE THREAD

**Issue by breuerfelix** [breuerfelix/jinflow#6]
hey guys,

the repo name was just a short idea cause i wanted to get started into coding and not think 3 days about the name of instapy v2 ...

i want you to write down some cool ideas about a new name for the repo !

i thouht about smth funny if you start the bot. it should be started from the cli in the future like this `getmefriends -u username -p password ...` so it would be cool to have a funny name BUT i would be cool with a regular name and maybe a name which corresponds to instapy :)

__what are your thoughts about a new name ??__

**Comment by SethRzeszutek** [comment]
I feel that including "friends" in the title is a bit misleading as usually its associated with followers not friends. I feel it is good to keep "Insta" in the name.
What about AutoInsta, InstaAuto, JInsta(Javascript+Instagram), JSgram, etc.

**Comment by riccardovalente** [comment]
agree...
How about JIG (javascript + IG) or Instanode

**Comment by tsgoff** [comment]
inflow
getflow
getify

**Comment by trooperas** [comment]
Hypergram

**Comment by SethRzeszutek** [comment]
> Hypergram

I don't mind it but I feel it adds a bit of confusion on what its for since we have Instagram and Telegram as very popular platforms. I even might recant my naming scheme that includes (some word)+gram.

**Comment by breuerfelix** [comment]
i love jinsta, jig and inflow .... cause they are short and they sound cool :dagger: 
the problem is, we need a name which is free as an npm package and jig and inflow are both taken ...

but i thought about jinflow (Javascript INstagram FLOW)

nvm just post all your ideas here and i will do a poll tomorrow !

**Comment by dimeloper** [comment]
what about instaty ? like instapy but with typescript :)

**Comment by breuerfelix** [comment]
https://linkto.run/p/TGWCLH31 vote for new name ! it has to be in lower case cause no cli program uses upper case :smile: multiple choice allowed and you can also add your own stuff !

**Comment by breuerfelix** [comment]
wow jinsta was the first from the list which i was able to publish to npm ...

i wanted to take getflow cause i really liked it but seems like there is a package called get-flow which was "too similar" to my package name... 

anyways ! welcome to jinsta !! :D
